[book]
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
multilingual = false
src = "src"
title = "The Tock Book"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css", "theme/pagetoc-tock.css"]
additional-js  = ["theme/pagetoc.js"]

[output.linkcheck]
optional = true